services:
  server:
    build:
      context: .
    ports:
      - '${APP_PORT}:80'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html
  db:
    image: mariadb
    restart: always
    user: root
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=example
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:3306
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      default: {}
  phpmyadmin:
    image: phpmyadmin
    ports:
      - ${PHP_ADMIN_PORT}:80
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_TCP_PORT=${DB_PORT}
      - MYSQL_UNIX_PORT=${DB_PORT}
networks:
  default:
    name: shared-db
    attachable: true
volumes:
  db-data: